spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ****
    username: ****
    password: ****

paimentprocessing:
  kafka:
    consumer:
      bootstrap-servers: 40.69.78.245:19092
      groupId: cashback
      topic: transactions

rest:
  api:
    card: http://****/card-service/api/v1/card/{id}
    client: http://****/client-service/api/v1/client/{id}
    program: http://****/loyalty-service/api/v1/program/{id}
    notification: http://****/notification-service/api/v1/client/{id}/message

sing: polovintsev-cashback-service