spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    username: sa
    password: sa
  kafka:
    consumer:
      bootstrap-servers: 40.69.78.245:19092
      groupId: cashback
      topic: transactions

#logging:
#  level:
#    org:
#      springframework:
#        kafka: debug
